/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'purchasedPlan' : [] | [HostingPackage],
}
export interface HostingPackage {
  'cpu' : string,
  'ram' : string,
  'storage' : string,
  'name' : string,
  'lifetime' : { 'oneYear' : null } |
    { 'fiveYears' : null },
  'websites' : bigint,
}
export interface HostingPlans {
  'vps' : Plan,
  'domainOnly' : Plan,
  'sharedPlan' : Plan,
  'dedicated' : Plan,
}
export interface Plan {
  'packages' : Array<HostingPackage>,
  'cost' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlans' : ActorMethod<[], HostingPlans>,
  'getPurchasedPlan' : ActorMethod<[], [] | [HostingPackage]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchasePlan' : ActorMethod<[HostingPackage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];