/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HostingPackage = IDL.Record({
  'cpu' : IDL.Text,
  'ram' : IDL.Text,
  'storage' : IDL.Text,
  'name' : IDL.Text,
  'lifetime' : IDL.Variant({ 'oneYear' : IDL.Null, 'fiveYears' : IDL.Null }),
  'websites' : IDL.Nat,
});
export const Account = IDL.Record({
  'id' : IDL.Text,
  'purchasedPlan' : IDL.Opt(HostingPackage),
});
export const Plan = IDL.Record({
  'packages' : IDL.Vec(HostingPackage),
  'cost' : IDL.Text,
  'name' : IDL.Text,
});
export const HostingPlans = IDL.Record({
  'vps' : Plan,
  'domainOnly' : Plan,
  'sharedPlan' : Plan,
  'dedicated' : Plan,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlans' : IDL.Func([], [HostingPlans], ['query']),
  'getPurchasedPlan' : IDL.Func([], [IDL.Opt(HostingPackage)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchasePlan' : IDL.Func([HostingPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HostingPackage = IDL.Record({
    'cpu' : IDL.Text,
    'ram' : IDL.Text,
    'storage' : IDL.Text,
    'name' : IDL.Text,
    'lifetime' : IDL.Variant({ 'oneYear' : IDL.Null, 'fiveYears' : IDL.Null }),
    'websites' : IDL.Nat,
  });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'purchasedPlan' : IDL.Opt(HostingPackage),
  });
  const Plan = IDL.Record({
    'packages' : IDL.Vec(HostingPackage),
    'cost' : IDL.Text,
    'name' : IDL.Text,
  });
  const HostingPlans = IDL.Record({
    'vps' : Plan,
    'domainOnly' : Plan,
    'sharedPlan' : Plan,
    'dedicated' : Plan,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlans' : IDL.Func([], [HostingPlans], ['query']),
    'getPurchasedPlan' : IDL.Func([], [IDL.Opt(HostingPackage)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchasePlan' : IDL.Func([HostingPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };