/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Plan {
    packages: Array<HostingPackage>;
    cost: string;
    name: string;
}
export interface HostingPlans {
    vps: Plan;
    domainOnly: Plan;
    sharedPlan: Plan;
    dedicated: Plan;
}
export interface HostingPackage {
    cpu: string;
    ram: string;
    storage: string;
    name: string;
    lifetime: Variant_oneYear_fiveYears;
    websites: bigint;
}
export interface Account {
    id: string;
    purchasedPlan?: HostingPackage;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_oneYear_fiveYears {
    oneYear = "oneYear",
    fiveYears = "fiveYears"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllAccounts(): Promise<Array<Account>>;
    getCallerUserRole(): Promise<UserRole>;
    getPlans(): Promise<HostingPlans>;
    getPurchasedPlan(): Promise<HostingPackage | null>;
    isCallerAdmin(): Promise<boolean>;
    purchasePlan(purchasedPlan: HostingPackage): Promise<void>;
}
import type { Account as _Account, HostingPackage as _HostingPackage, HostingPlans as _HostingPlans, Plan as _Plan, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllAccounts(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccounts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccounts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlans(): Promise<HostingPlans> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlans();
                return from_candid_HostingPlans_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlans();
            return from_candid_HostingPlans_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchasedPlan(): Promise<HostingPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchasedPlan();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchasedPlan();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchasePlan(arg0: HostingPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePlan(to_candid_HostingPackage_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePlan(to_candid_HostingPackage_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Account_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_HostingPackage_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostingPackage): HostingPackage {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_HostingPlans_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostingPlans): HostingPlans {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Plan_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plan): Plan {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HostingPackage]): HostingPackage | null {
    return value.length === 0 ? null : from_candid_HostingPackage_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vps: _Plan;
    domainOnly: _Plan;
    sharedPlan: _Plan;
    dedicated: _Plan;
}): {
    vps: Plan;
    domainOnly: Plan;
    sharedPlan: Plan;
    dedicated: Plan;
} {
    return {
        vps: from_candid_Plan_n14(_uploadFile, _downloadFile, value.vps),
        domainOnly: from_candid_Plan_n14(_uploadFile, _downloadFile, value.domainOnly),
        sharedPlan: from_candid_Plan_n14(_uploadFile, _downloadFile, value.sharedPlan),
        dedicated: from_candid_Plan_n14(_uploadFile, _downloadFile, value.dedicated)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packages: Array<_HostingPackage>;
    cost: string;
    name: string;
}): {
    packages: Array<HostingPackage>;
    cost: string;
    name: string;
} {
    return {
        packages: from_candid_vec_n16(_uploadFile, _downloadFile, value.packages),
        cost: value.cost,
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    purchasedPlan: [] | [_HostingPackage];
}): {
    id: string;
    purchasedPlan?: HostingPackage;
} {
    return {
        id: value.id,
        purchasedPlan: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.purchasedPlan))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cpu: string;
    ram: string;
    storage: string;
    name: string;
    lifetime: {
        oneYear: null;
    } | {
        fiveYears: null;
    };
    websites: bigint;
}): {
    cpu: string;
    ram: string;
    storage: string;
    name: string;
    lifetime: Variant_oneYear_fiveYears;
    websites: bigint;
} {
    return {
        cpu: value.cpu,
        ram: value.ram,
        storage: value.storage,
        name: value.name,
        lifetime: from_candid_variant_n9(_uploadFile, _downloadFile, value.lifetime),
        websites: value.websites
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oneYear: null;
} | {
    fiveYears: null;
}): Variant_oneYear_fiveYears {
    return "oneYear" in value ? Variant_oneYear_fiveYears.oneYear : "fiveYears" in value ? Variant_oneYear_fiveYears.fiveYears : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HostingPackage>): Array<HostingPackage> {
    return value.map((x)=>from_candid_HostingPackage_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n4(_uploadFile, _downloadFile, x));
}
function to_candid_HostingPackage_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostingPackage): _HostingPackage {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cpu: string;
    ram: string;
    storage: string;
    name: string;
    lifetime: Variant_oneYear_fiveYears;
    websites: bigint;
}): {
    cpu: string;
    ram: string;
    storage: string;
    name: string;
    lifetime: {
        oneYear: null;
    } | {
        fiveYears: null;
    };
    websites: bigint;
} {
    return {
        cpu: value.cpu,
        ram: value.ram,
        storage: value.storage,
        name: value.name,
        lifetime: to_candid_variant_n19(_uploadFile, _downloadFile, value.lifetime),
        websites: value.websites
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_oneYear_fiveYears): {
    oneYear: null;
} | {
    fiveYears: null;
} {
    return value == Variant_oneYear_fiveYears.oneYear ? {
        oneYear: null
    } : value == Variant_oneYear_fiveYears.fiveYears ? {
        fiveYears: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
